name: "Test Action"

on:
  workflow_dispatch:

jobs:
  notify:
    name: Test Action
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Notify Microsoft Teams Channel - Success
        uses: burnsra/teams-notify-action@v1.0.0
        with:
          TEAMS_URI: ${{ secrets.TEAMS_URI }}
          TEAMS_MSG_TITLE: "Test Title (Success)"
          TEAMS_MSG_SUMMARY: "This is an example notification from the Teams Notify Action"
          TEAMS_MSG_TYPE: "success"
      - name: Notify Microsoft Teams Channel - Info
        uses: burnsra/teams-notify-action@v1.0.0
        with:
          TEAMS_URI: ${{ secrets.TEAMS_URI }}
          TEAMS_MSG_TITLE: "Test Title (Info)"
          TEAMS_MSG_SUMMARY: "This is an example notification from the Teams Notify Action"
          TEAMS_MSG_TYPE: "info"
      - name: Notify Microsoft Teams Channel - Failure
        uses: burnsra/teams-notify-action@v1.0.0
        with:
          TEAMS_URI: ${{ secrets.TEAMS_URI }}
          TEAMS_MSG_TITLE: "Test Title (Failure)"
          TEAMS_MSG_SUMMARY: "This is an example notification from the Teams Notify Action"
          TEAMS_MSG_TYPE: "failure"